name: CICD

on:
  workflow_dispatch:
    inputs:
      environment:
        description: This is the environment value where this workflow runs
        default: 'dev'
        required: true
        type: choice
        options:
          - dev
          - prod
          - staging
jobs:
  code:
     runs-on: ubuntu-latest
     steps:
       - name: checkout code
         run: echo "Code clone from Github"
  build:
      needs: [code]
      runs-on: ubuntu-latest
      steps:
       - name: Build Docker Container
         run: echo "Docker Container Build"
  test:
      needs: [build]
      runs-on: ubuntu-latest
      steps:
       - name: test the container
         run: echo "Testing the container"
    
  deploy:
       needs: [test]
       runs-on: ubuntu-latest
       steps:
        - name: Deployment
          run: echo "Deploy the app"
